### PR TITLE
Manage Session Cookies

### PR DESCRIPTION
**Pull request by tomykho**

### CODE REVIEW

**Comment by jeromegamez** [comment]
Uuuh, this looks very nice (also your other PR on the tokens library)! 🥰  I'll check out both locally and integrate them with each other (of course making sure the attribution stays with you) hopefully soon - I'm currently a little bit short on time, but expect this not to take _too_ long 🤞

**Comment by tomykho** [comment]
> Uuuh, this looks very nice (also your other PR on the tokens library)!  I'll check out both locally and integrate them with each other (of course making sure the attribution stays with you) hopefully soon - I'm currently a little bit short on time, but expect this not to take _too_ long

Thanks!
Do you mind if I create another PR on https://github.com/kreait/laravel-firebase for laravel custom auth driver and provider using session cookie?

**Comment by jeromegamez** [comment]
I wouldn't just yet, we don't know yet how the code will look like once it's merged into the SDK. For example I think I should migrate the token lib to PHP 7.4 before anything, I'm currently having trouble with it and it's already messy enough 😅

**Comment by jeromegamez** [comment]
I just added the session cookie generation with https://github.com/kreait/firebase-php/commit/b1e27138ed2b2ac8655826e4d8c7317901a3cfee - it's implemented differently than in your PR, but since you brought this in, I added you as a co-author and will do the same with the verification part, if that's okay with you 🤞

It's taking longer than originally anticipated (I currently don't have many resources for Open Source) but it will arrive in the SDK eventually 😅

**Comment by esseplore-it** [comment]
@jeromegamez Thanks! May I know how to [Verify session cookie and check permissions](https://firebase.google.com/docs/auth/admin/manage-cookies#verify_session_cookie_and_check_permissions) using your implementation?

**Comment by tomykho** [comment]
@jeromegamez Thanks! May I know how to [Verify session cookie and check permissions](https://firebase.google.com/docs/auth/admin/manage-cookies#verify_session_cookie_and_check_permissions) using your implementation?

**Comment by tomykho** [comment]
This is what I did last time https://github.com/tomykho/firebase-tokens-php/commit/789f0618dd1f00175c23b168479351da357bf41f

**Comment by arma7x** [comment]
https://github.com/kreait/firebase-tokens-php/blob/1.16.1/src/Firebase/Auth/Token/Verifier.php

File: SessionCookieVerifier.php 
Error: Call to undefined method Firebase\Auth\Token\Verifier::verifySessionCookie()

**Comment by jeromegamez** [comment]
Implemented with 31c05665189424cd5c4a76d7cee8d3eadedabcf6 - thanks again!

**Pull request closed without merging**
