### PR TITLE
Introduce Firebase Cloud Messaging

### LINKED ISSUE #126: Support Firebase Cloud Messaging (FCM)
See https://firebase.google.com/docs/cloud-messaging/send-message

### PR DESCRIPTION
**Pull request by jeromegamez**
Closes #126 

Really early progress, things could change a lot! 

Here is my test script:

```php
<?php

declare(strict_types=1);

use Kreait\Firebase;
use Kreait\Firebase\Exception\MessagingException;
use Kreait\Firebase\Messaging\ConditionalMessage;
use Kreait\Firebase\Messaging\MessageToRegistrationToken;
use Kreait\Firebase\Messaging\MessageToTopic;
use Kreait\Firebase\Util\JSON;

require_once __DIR__.'/vendor/autoload.php';

$serviceAccount = Firebase\ServiceAccount::fromJsonFile(__DIR__.'/tests/_fixtures/test_credentials.json');

$firebase = (new Firebase\Factory())
    ->withServiceAccount($serviceAccount)
    ->create();

$messaging = $firebase->getMessaging();

$data = ['foo' => 'bar'];

$notification = [
    'title' => 'Notification title',
    'body' => 'Notification body',
];

$deviceRegistrationToken = '...';

$messages = [
    MessageToTopic::create('my-topic')
        ->withData($data)
        ->withNotification($notification),

    [
        'topic' => 'another-topic',
        'data' => $data,
        'notification' => $notification,
    ],

    MessageToRegistrationToken::create($deviceRegistrationToken)
        ->withData($data)
        ->withNotification($notification),

    [
        'token' => $deviceRegistrationToken,
        'data' => $data,
        'notification' => $notification,
    ],

    ConditionalMessage::create("'dogs' in topics || 'cats' in topics")
        ->withData($data)
        ->withNotification($notification),

    [
        'condition' => "'dogs' in topics || 'cats' in topics",
        'data' => $data,
        'notification' => $notification,
    ],
];

array_map(function ($message) use ($messaging) {
    try {
        echo 'Sending '.PHP_EOL.JSON::encode($message).PHP_EOL;
        $messaging->send($message);
        echo 'SUCCESS'.PHP_EOL;
    } catch (MessagingException $e) {
        echo 'ERROR: '.$e->getMessage();
    }
}, $messages);
```

## Todo

- [x] Send to topic
- [x] Sent to token
- [x] Send conditional message
- [x] Catch API exceptions
- [ ] Add documentation
- [x] Add tests

### CODE REVIEW

**Comment by sroze** [comment]
I can confirm it does work, at least for sending notifications to topic 💃 (I have only tested on iOS though, I have a doubt on Android and its "notification channel").

**Comment by jeromegamez** [comment]
@sroze Thank you so much for checking the new feature out - if you have time, could you pull the branch and test again, please? 😊 Please note the changed manual test script in the PR description - I've added messages to tokens and conditional messages, and different means to create them (I dread the docs-part of this PR already :D).

Unfortunately, I don't have an app or devices to test all this with - so sending messages to single tokens directly *should* work, but I can not test it with certainty.

**Comment by jeromegamez** [comment]
I am postponing the Android/APNS/WebPush configs for now so that I can create a release with basic support earlier. The device specific configuration will then come with a follow-up release. That way, if more people use the feature, I can react better.

**Comment by jeromegamez** [comment]
I just added support for Conditional Messages and Messages to Registration Tokens (the latter I can't test due to the lack of devices :)) and the corresponding Unit/Integration tests.

Please note the changed manual test script in the PR description.

**Comment by Zeromax** [comment]
@jeromegamez thanks for this implementation.

Just a question: Is ther any Reason why the three message types have static funtions? this can be done with `(new MessageType($condition))->fromArray($data)`. I can not see any benefit in static methods here.

**Comment by Zeromax** [comment]
@jeromegamez I can confirm that sending a message to a single device registration token is working. (tested for Android)

Well done ;)

**Comment by jeromegamez** [comment]
@Zeromax Thank you for your Feedback, I really appreciate it and am glad that things seem to be working.

Concerning the static methods: I will even make the constructors private before releasing the FCM feature ^^. Using static factory methods instead of the constructor makes the classes more easily extensible. If, in the future, a class needs more or less hard dependencies, this allows me to change the constructor at will, without the need to create a new major release (because of SemVer).

**Comment by yavuzkoca** [comment]
How to get $deviceRegistrationToken?

**Comment by Zeromax** [comment]
@yavuzkoca you have to register your device/APP in firebase, then you get this token. With this token you can send notifications to your device

**Comment by Zeromax** [comment]
@jeromegamez Ok, I get your point. I'm fine with it.

**Comment by yavuzkoca** [comment]
So, I need to save this device token to firebase database when user opens my application. This part is fine, However, I don't understand how can I send messages to all Android users from Firebase Console without knowing their device IDs?

**Comment by Zeromax** [comment]
I think this article may help you: https://firebase.google.com/docs/cloud-messaging/android/send-multiple
You only can send messages to Devices you are knowing. Otherwise this would be a security issue ;)

**Comment by jeromegamez** [comment]
Merged with 55cf98e914239346805c048298992c5563ab3d15 and released as 4.5.0 with 7c32e808b50f610f3ef6cfd9b6e57033032a4cb9

Documentation can be found at https://firebase-php.readthedocs.io/en/latest/cloud-messaging.html

**Comment by Zeromax** [comment]
@jeromegamez Thank you!

**Pull request closed without merging**
