### PR TITLE
Get and Set Firebase Rules

### PR DESCRIPTION
**Pull request by bennyt2**
Get and Set Firebase Rules via the REST API, as noted in this documentation: https://firebase.google.com/docs/database/rest/app-management

This is a proposed fix for Issue #132.

### CODE REVIEW

**Comment by jeromegamez** [comment]
Ooooh, this looks nice, I like it a lot already. As soon as I get back to my computer, I will check it out and play it through once.

Would you mind adding a small section to the docs as well? (The incoming merge doesn't depend on it :))

**Comment by bennyt2** [comment]
Docs added. I think I did them right. I had trouble installing Sphinx on my machine, so I wasn't able to review the formatting locally. Let me know if they need to be changed or improved.

**Comment by jeromegamez** [comment]
Thank you Ben! There are some minor issues, but nothing serious. I'll rewrite the docs a little, and I will also add some try/catch blocks to the code - for example: if the first `rules` key is missing, the API returns an error, which is currently not catched. It would perhaps make sense to abstract the first field away. So the behaviour will probably change slightly.

Anyways, I will merge your changes and add mine afterwards. Thank you very much!

**Comment by bennyt2** [comment]
@jeromegamez Thank you for merging this code, and for your speedy and thoughtful replies. Have a great weekend!

**Comment by jeromegamez** [comment]
@bennyt2 I have made some (yet unreleased) changes to the code and the documentation, you can see them here:

Commit: https://github.com/kreait/firebase-php/commit/c2128d61c3741760a6dcb13b9b089adb7f61e565
Docs: http://firebase-php.readthedocs.io/en/latest/realtime-database.html#database-rules

**Comment by bennyt2** [comment]
@jeromegamez I tested this out in my app and it works great. I like that you made the RuleSet class. Makes it much easier to visualize, and forces people to use Rules correctly. Thank you!!

**Pull request merged**
