### PR TITLE
Use FCM HTTP V1 Api for Batch Messaging

### LINKED ISSUE #804: Discontinued FCM Messaging API
### Describe the bug

Messaging `sendMulticast()` method uses discontinued Google FCM API.

**Ref**: https://github.com/firebase/firebase-admin-node/pull/2138

Suggest me if there is any alternate solution like using different method to send message to multiple devices.

### Installed packages

```json
{
    "require": {
        "kreait/firebase-php": "^7.2.1",
    }
}
```

### PHP version and extensions

```shell
composer                2.5.5     Composer package
composer-plugin-api     2.3.0     The Composer Plugin API
composer-runtime-api    2.2.2     The Composer Runtime API
ext-calendar            8.2.7     The calendar PHP extension
ext-ctype               8.2.7     The ctype PHP extension
ext-curl                8.2.7     The curl PHP extension
ext-date                8.2.7     The date PHP extension
ext-dom                 20031129  The dom PHP extension
ext-exif                8.2.7     The exif PHP extension
ext-ffi                 8.2.7     The FFI PHP extension
ext-fileinfo            8.2.7     The fileinfo PHP extension
ext-filter              8.2.7     The filter PHP extension
ext-ftp                 8.2.7     The ftp PHP extension
ext-gd                  8.2.7     The gd PHP extension
ext-gettext             8.2.7     The gettext PHP extension
ext-gmp                 8.2.7     The gmp PHP extension
ext-hash                8.2.7     The hash PHP extension
ext-iconv               8.2.7     The iconv PHP extension
ext-igbinary            3.2.13    The igbinary PHP extension
ext-imagick             3.7.0     The imagick PHP extension
ext-intl                8.2.7     The intl PHP extension
ext-json                8.2.7     The json PHP extension
ext-libxml              8.2.7     The libxml PHP extension
ext-mbstring            8.2.7     The mbstring PHP extension
ext-openssl             8.2.7     The openssl PHP extension
ext-pcntl               8.2.7     The pcntl PHP extension
ext-pcre                8.2.7     The pcre PHP extension
ext-pdo                 8.2.7     The PDO PHP extension
ext-pdo_pgsql           8.2.7     The pdo_pgsql PHP extension
ext-pdo_sqlite          8.2.7     The pdo_sqlite PHP extension
ext-pgsql               8.2.7     The pgsql PHP extension
ext-phar                8.2.7     The Phar PHP extension
ext-posix               8.2.7     The posix PHP extension
ext-random              8.2.7     The random PHP extension
ext-readline            8.2.7     The readline PHP extension
ext-redis               5.3.7     The redis PHP extension
ext-reflection          8.2.7     The Reflection PHP extension
ext-session             8.2.7     The session PHP extension
ext-shmop               8.2.7     The shmop PHP extension
ext-simplexml           8.2.7     The SimpleXML PHP extension
ext-sockets             8.2.7     The sockets PHP extension
ext-sodium              8.2.7     The sodium PHP extension
ext-spl                 8.2.7     The SPL PHP extension
ext-sqlite3             8.2.7     The sqlite3 PHP extension
ext-sysvmsg             8.2.7     The sysvmsg PHP extension
ext-sysvsem             8.2.7     The sysvsem PHP extension
ext-sysvshm             8.2.7     The sysvshm PHP extension
ext-tokenizer           8.2.7     The tokenizer PHP extension
ext-xdebug              3.2.0     The xdebug PHP extension
ext-xml                 8.2.7     The xml PHP extension
ext-xmlreader           8.2.7     The xmlreader PHP extension
ext-xmlwriter           8.2.7     The xmlwriter PHP extension
ext-xsl                 8.2.7     The xsl PHP extension
ext-zend-opcache        8.2.7     The Zend OPcache PHP extension
ext-zip                 1.21.1    The zip PHP extension
ext-zlib                8.2.7     The zlib PHP extension
lib-curl                7.81.0    The curl library
lib-curl-libssh         0.9.6     curl libssh version
lib-curl-openssl        3.0.2     curl OpenSSL version (3.0.2)
lib-curl-zlib           1.2.11    curl zlib version
lib-date-timelib        2022.07   date timelib version
lib-date-zoneinfo       0         zoneinfo ("Olson") database for date
lib-fileinfo-libmagic   540       fileinfo libmagic version
lib-gd                  2.3.3     The gd library
lib-gmp                 6.2.1     The gmp library
lib-iconv               2.35      The iconv library
lib-icu                 70.1      The ICU unicode and globalization support library
lib-icu-cldr            40        ICU CLDR project version
lib-icu-unicode         14.0.0    ICU unicode version
lib-icu-zoneinfo        2023.3    zoneinfo ("Olson") database for icu
lib-imagick-imagemagick 6.9.11.60 The imagick-imagemagick library
lib-libsodium           1.0.18    The libsodium library
lib-libxml              2.9.14    libxml library version
lib-libxslt             1.1.34    The libxslt library
lib-libxslt-libxml      2.9.13    libxml version libxslt is compiled against
lib-mbstring-libmbfl    1.3.2     mbstring libmbfl version
lib-mbstring-oniguruma  6.9.7     mbstring oniguruma version
lib-openssl             3.0.2     OpenSSL 3.0.2 15 Mar 2022
lib-pcre                10.40     The pcre library
lib-pcre-unicode        14.0.0    PCRE Unicode version support
lib-pdo_pgsql-libpq     14.8      libpq for pdo_pgsql
lib-pdo_sqlite-sqlite   3.37.2    The pdo_sqlite-sqlite library
lib-sqlite3-sqlite      3.37.2    The sqlite3-sqlite library
lib-zip-libzip          1.7.3     The zip-libzip library
lib-zlib                1.2.11    The zlib library
php                     8.2.7     The PHP interpreter
php-64bit               8.2.7     The PHP interpreter, 64bit
php-ipv6                8.2.7     The PHP interpreter, with IPv6 support
```

### Steps to reproduce the issue.

```php
foreach (array_chunk($tokens->pluck('token')->all(), 100) as $chunk) {
    $report = $this->messaging->sendMulticast($message, $chunk);

    foreach ($report->failures()->getItems() as $failure) {
        $this->parseFailureResponse($user, $failure);
    }
}
```

### Error message/Stack trace

```shell
-
```

### Additional information

I have received a mail from Google to alert me about the usage of discontinued API in one of my project.

FCM

### PR DESCRIPTION
**Pull request by jeromegamez**
Closes #804

:octocat:

### CODE REVIEW

**Comment by rudyzeinoun** [comment]
Thanks for the amazingly fast resolution.
Is the [max devices limit](https://github.com/kreait/firebase-php/blob/7.x/src/Firebase/Messaging.php#L87) still needed? The new API doesn't use batching, so any number of devices can be sent, as long as the messages fit altogether in memory. Right?

**Comment by jeromegamez** [comment]
Theoretically not, but as far as I remember, I saw the limit remained in the Admin Node SDK as well, but it could have been an oversight on their part 🤔

I don't know what it would do to memory consumption and execution time, though, and if this is something that I should consider a developer to be aware of (and chunk the messages beforehand) or if I should wait until someone opens an issue saying "I tried to send 1 Million messages and my server crashed" 😅.

What do you think?

**Comment by rudyzeinoun** [comment]
I'm subjective because I will eventually need to do this myself anyway. But I can imagine anyone sending to 499 tokens will need this after a few days of reaching 500 tokens. Use cases like notifying followers, notifying a broadcast channel (although topics exist for that). They can easily exceed 500.

If it's left for the developer to chunk them, there will be 2 levels of Promises (one from the library and another from the developer's project). It would be harder on beginners for sure.

**Comment by jeromegamez** [comment]
That's a good argument - and now that you say it, I forgot that I was thinking about chunking the messages in the SDK a while ago - I'm confident the limit was there due to the batch API supporting only multipart requests (and responses) to avoid too large message bodies, which now shouldn't be an issue anymore.

Long story short: I'll remove the limit 💪🏻

**Comment by rudyzeinoun** [comment]
That was easy 😁 thank you

**Comment by jeromegamez** [comment]
I'm not in the business of making things difficult 😅. You're welcome, and thanks a lot for your valuable feedback! 🌺

**Comment by cutekanudo21** [comment]
To confirm its load, today i have tested it upto 3000 invalid tokens and two real tokens, it takes sometime in loading but request completes. Then i tried with 5000 invalid tokens / 2 real token and it crashes with http error 500. (FYI: VPS with 4v core & 8GB RAM) 

Here is my code: `<?php

declare(strict_types=1);

require 'vendor/autoload.php';

use Kreait\Firebase\Factory;

putenv('GOOGLE_APPLICATION_CREDENTIALS=./fcmtest.json');

$fcm = (new Factory())->createMessaging();

/*** TOKEN ARRAY ***/
$deviceTokens = [];

$deviceTokens[] = 'REAL_TOKEN_1'; // This is real valid token

for ($i = 1; $i <= 5000; $i++) {
    $deviceTokens[] = 'dummy_token_' . $i; // 5000 dummy token just for a testing...

$deviceTokens[] = 'REAL_TOKEN_2'; // This is real valid token

$message = [
    'notification' => [
        'title' => 'Notification Title',
        'body' => 'Notification Body',
        'image' => 'https://example.com/test.jpg',
    ],
    'webpush' => [
        'fcm_options' => [
            'link' => 'https://example.com'
        ],
    ],
];

$report = $fcm->sendMulticast($message, $deviceTokens);

// echo 'Successful sends: '.$report->successes()->count().PHP_EOL;
// echo 'Failed sends: '.$report->failures()->count().PHP_EOL;

?>`

**Comment by cutekanudo21** [comment]
Another question related to your answer yesterday here: https://stackoverflow.com/questions/76563436/firebase-http-v1-api-and-no-batch-send-anymore/76568887#76568887

how to print oauth 2 access token in that pure php code, so that we can save that token for an hour, so that we can't exceeded quota limit of 50/100 refresh token.

**Comment by jeromegamez** [comment]
@rudyzeinoun This is what I was afraid about 😅 (@cutekanudo21, this has nothing to you with your valid issue)

@cutekanudo21 Without knowing the exact reason for the error ("Error 500" allows just guesswork), it might be that the PHP max execution time was exceeded or that the memory of your server was exhausted.

In real life, you would certainly not have 5K invalid tokens, but even with valid tokens the problem would probably be the same. You should inspect the actual reason for the error, but if it's the max execution time, using a queue _might_ help. In case of memory exhaustion, chunking the tokens and calling the method with batches _might_ work.

In general, it is recommended to use topics when sending messages to a large amount of devices.

As to your second question - in pure PHP (I assume you mean without using the SDK), you can wrap the Google Credentials in the [`FetchAuthTokenCache` class](https://github.com/googleapis/google-auth-library-php/blob/main/src/FetchAuthTokenCache.php). Here's how it's done in the SDK: https://github.com/kreait/firebase-php/blob/fc739b07d7343d819840e84cc562de3e8d856948/src/Firebase/Factory.php#L547

**Comment by cutekanudo21** [comment]
Thanks for your reply. I also tried increasing max exec time to 120 and memory limit: 512m but still it can't handle 7000.

In my Plesk panel, i checked server resources statistics but it's just use some % only, no any server load actually.

If there's any other php settings required let me know.

So using your SDK, I think no need to save token because you may save it in cache for an hour?

**Comment by jeromegamez** [comment]
You still have to configure the cache as described here: https://firebase-php.readthedocs.io/en/stable/setup.html#authentication-tokens

If your plesk server grants you access to the PHP error log, you should be able to see there what caused the 500 error. Server configuration is out of scope of what I can provide free support for, though, I hope you understand 🙏🏻

**Pull request merged**
