### PR TITLE
[docs] overview - do not require specific version, let composer pick one

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by jeromegamez** [comment]
I added the version on purpose to reduce frequent issues reported by people requiring the SDK in an unsupported PHP environment, e.g. https://github.com/kreait/firebase-php/issues/66, https://github.com/kreait/firebase-php/issues/75, https://github.com/kreait/firebase-php/issues/95.

When using PHP 5.x, a `composer require kreait/firebase-php` would install version 1.x, so I prefer keeping the constraint in the documentation.

Thank you for the PR nonetheless, Tomas, I do really appreciate that you took the time to create it!

:octocat:

**Comment by TomasVotruba** [comment]
@jeromegamez How can it be installed in wrong PHP version? That should be handled in `composer.json`, right?

**Comment by jeromegamez** [comment]
Composer will check the current PHP version and install the latest version supported for that PHP version - as Release 1.x supports PHP ^5.5 (see https://packagist.org/packages/kreait/firebase-php#1.2.2), composer would use that one.

**Comment by TomasVotruba** [comment]
And Relase 1.1 doesn't support PHP 5.5? So `composer.json` is invalid there?

**Comment by jeromegamez** [comment]
Release 1.1 does support PHP 5.5. The point is: depending on the PHP version `composer require kreait/firebase-php` will not always install the same version. `composer require kreait/firebase-php ^3.0` however will install always install version 3.x (on PHP ^7.0) or fail (on PHP <7) with the message that this PHP version is not supported.

**Comment by TomasVotruba** [comment]
I see, the documentations is out of sync.

Now it makes sense, thanks :)

**Pull request closed without merging**
