### PR TITLE
Fix CS

### PR DESCRIPTION
**Pull request by szepeviktor**
📢 Rare event!

Only 1 type of error: `function_declaration`

Please consider running php-cs-fixer on each push. These commits affecting many files are not the nicest things in the world.

### CODE REVIEW

**Comment by jeromegamez** [comment]
I usually do,  it thanks for the suggestion. That must have been a rule I forgot to migrate when I changed the rules a few weeks ago, I'll check

**Comment by szepeviktor** [comment]
There is an imperfect way.
If you run php-cs-fixer in a workflow like `php-cs-fixer || true` you can get check annotations in PR diffs but still have a ✔️

image

**Comment by jeromegamez** [comment]
It might be imperfect, but that's how I do it. CS is something I usually run when I push, and when I forget, I do it afterwards and (brace yourself) might even force-push it.

By the way, when I run PHP CS Fixer, it don't get the same report

CleanShot 2023-10-28 at 22 51 10@2x

**Comment by jeromegamez** [comment]
I take that back, it reported them when I updated the composer dependencies :D

**Comment by szepeviktor** [comment]
All problems come from humans.
That is why I've spent the last decade with inserting QA tools between humans and the application/package.

**Comment by jeromegamez** [comment]
Thanks!

**Comment by jeromegamez** [comment]
Oh, I know and I agree, and in my professional work-life I apply the same principles. But this started as a personal project a long time ago and still is my playground, and I like doing things by hand, and nobody has complained so far. Until I get paid for my open source work so that I can make a living, I will continue to do work on my open source projects as if they were a hobby, which they obviously are.

**Comment by szepeviktor** [comment]
> Oh, I know and I agree, and in my professional work-life I apply the same principles.

Please give me something to do, where they allow me - without compensation - to clean things up from the ground up.
I pay you €1000/project.

**Comment by jeromegamez** [comment]
I'm not sure how you mean this, so I don't dare to reply 😅

**Comment by szepeviktor** [comment]
In the last 3 years I had ~8 hours work/week. I'd like to work in a team to make others happy.
I work with underlying technologies - the things no one has time for.

**Comment by szepeviktor** [comment]
... while doing secret guerrilla monitoring I've learned that almost no team is in control of their software product. The Software has a grip on the team!!

I could tame any software that is made from my bytes (0-255).

**Pull request merged**
