### PR TITLE
Implementing FCM sendAll and sendMulticast APIs.

### PR DESCRIPTION
**Pull request by PokeGuys**
The sendMulticast() API uses the sendAll() method to send a single message to a batch of 100 tokens.

### CODE REVIEW

**Comment by jeromegamez** [comment]
Woah, thanks for the time and effort you put into this, this looks really good! As this is quite a big contribution, it will take some time to go through.

Some things I noticed right away:

- Could you please rework the PR to consist of multiple, more atomic commits? For example the refactoring of the exception handling, or the addition of middlewares and other components not strictly related to the feature itself. This would allow me to cherry-pick them into the master branch to make the PR gradually smaller and easier to process.
- I noticed that the MultipartResponse is copied from https://github.com/dickolsson/http-multipart - the repo has no open source license included, so we can‘t use it as it is, unless the author adds one, so that we can attribute him correctly, pull it in as an additional dependency and/or Support the effort to merge this into the Guzzle directly.
- I avoided to have abstract classes so far, perhaps we could think of another solution here, e.g. an `ApiClient` interface with a `GuzzleApiClient` implementation that then could be used in all other components making requests (composition over inheritance). This could also be done in a separate PR.

I will have a deeper look once I‘m at my computer. 

If you‘re willing to continue to work on this, please consider joining the kreait discord server (link in the readme file) to have a better hold on each other :)

If you don‘t have the time to continue on this feature, please let me know, and I will take over (making sure you get the attribution for the feature that you deserve) - otherwise, I will start a more detailed review as soon as I can.

Thanks again, I love what you‘ve done so far! 🌺

**Comment by PokeGuys** [comment]
OK. If I want to rework the PR, what should I do? just close this PR, create a new branch, do it again?

**Comment by jeromegamez** [comment]
No no, let‘s stay here, and continuously rebase and force-push

**Comment by PokeGuys** [comment]
This package https://github.com/dickolsson/http-multipart. We can't use it as a dependency. It strictly required the php version must be ~5.4 and the middleware is outdated. It is for Guzzle 5 / 4 only.

**Comment by jeromegamez** [comment]
Alright, we‘ll deal with this later ^^

Could you please rebase your branch with the current master branch, resolve the merge conflicts, run `vendor/bin/php-cs-fixer fix` And force push?

**Comment by jeromegamez** [comment]
I‘m currently implementing the feature in a slightly different way (and making the groundwork to refactor all API requests, not just for the messaging component), and your PR is a *huge* help!

No need for you to continue on this, but I want to let you know that you will get full Co Author attribution for this! (see https://help.github.com/en/articles/creating-a-commit-with-multiple-authors)

**Comment by jeromegamez** [comment]
It took me a while, but I think it was worth it!

As promised, you are now immortalized in the repo's history in https://github.com/kreait/firebase-php/commit/7713753c296a6d0cc7ab514171bc513bc0ec8a1c 

Thanks again @PokeGuys, this is much appreciated! 🌺

**Pull request closed without merging**
