### PR TITLE
Create docs workflow

### PR DESCRIPTION
**Pull request by szepeviktor**
For now it will find broken links.

Later it could be enhanced with sphinx-lint!

### CODE REVIEW

**Comment by szepeviktor** [comment]
💡 There is a standard for domains for testing.
https://www.rfc-editor.org/rfc/rfc2606.html#section-2

For now I will ignore _Jérôme-domains_ :)

**Comment by jeromegamez** [comment]
> For now I will ignore _Jérôme-domains_ :)

Ah, I know of that one, but please remember, this project is quite old already. ("Jérôme-Domains", stop mocking me! 🤨😂)

The `domain.tld` ones are easy to fix, and finding the once-working links to the Firebase Docs are a great addition (I think this should be checked regularly, not within PRs, though. And there are some links that I wouldn't like to change (e.g. `https://my-project-default-rtdb.firebaseio.com`, in fact all `*.firebaseio.com` domains).

I think all this would require a `.lycheeignore` file.

And you do realize you have to fix all this now, do you! (Just kidding, I can take over the PR from here on and fix what you didn't cause)

**Comment by szepeviktor** [comment]
image

**Comment by jeromegamez** [comment]
Merged with 703c3e34c694a806603c998391b0bd205214b886, ad6645f45d02cf0e6af34ccd91b7151c37214905 and 8f28a9939a341514f471c29e072d8c72dd655064.

Thanks!

**Comment by szepeviktor** [comment]
Glad to contribute.

**Pull request closed without merging**
