### PR TITLE
Support Firestore

### PR DESCRIPTION
**Pull request by morrislaptop**
Supports creating and getting documents. 

Nowhere finished yet, but thought I would give a heads up that I'll be working on this as I need it for my current project. 

Addresses #117 

- [x] Get
- [x] Set
- [ ] Delete
- [ ] Add
- [ ] Transactions (beginTransaction, commit, rollback)
- [ ] Reference value support
- [ ] Batch Get
- [ ] List Documents
- [ ] Query
- [ ] Order
- [ ] Limit
- [ ] Indexes (create, delete, list, get)

### CODE REVIEW

**Comment by morrislaptop** [comment]
@jeromegamez @aloisejulian @ChrisSmith5 @anelad @etopian @P110 @riyuk any thoughts?

**Comment by jeromegamez** [comment]
Thanks for all the work you've already put into this, @morrislaptop, I really appreciate it!

However, as I said in https://github.com/kreait/firebase-php/issues/117#issuecomment-384626919, I am not keen of re-implementing of what's already being actively maintained in https://github.com/GoogleCloudPlatform/google-cloud-php-firestore, just to not have the requirement of the grpc extension.

Please keep in mind that once this PR would be merged, I would have to maintain it as well as keep track of changes in the copy-pasted classes (e.g. the ValueMapper class).

I currently see two solutions here:

- You could fork the PHP Admin SDK and maintain the Firestore part of it. I would then try to ensure that e.g. the factory and the Firebase class remain extensible, as well as link to your fork.

- We extend the factory and the Firebase class to allow instantiating/using a FirestoreStore instance with some `class_exists('\Google\Cloud\Firestore\FirestoreClient')` checks, and add `google/cloud-firestore` to the "suggest" section in the composer.json file and in the documentation.

I do want to keep the entrypoint to Firebase with PHP low by not requiring the grpc extension by default, but I don't think duplicating the complex Firestore functionality is the best solution for this, especially since the work to provide the functionality has already been done by Google.

What do you think?

**Comment by jeromegamez** [comment]
The second solution (providing a gateway to `google/cloud-firestore` if the class exists) is something that's on my todo list already, and I would put it on the top of the list if you want to keep using this SDK, are ready to install the grpc extension and just need a way to get access to Firestore.

**Comment by morrislaptop** [comment]
Hi @jeromegamez ,

I think the top goal is to avoid the grpc requirement. It is a massive barrier to entry.

So that just leaves the first solution. Just to be clear my approach will be:

* Creating a separate package `morrislaptop/firestore-php`
* Extend `Kreait\Firebase\Factory` to create a `Firestore` instance which is passed to:
* An extended `Kreait\Firebase` with a `getFirestore()` method

Users could then use simply use `Morrislaptop\Firestore\Factory` to interact with Firestore and all the other stuff this library provides. 

Sound like a plan?

**Comment by jeromegamez** [comment]
Sounds like a plan!

**Comment by morrislaptop** [comment]
WIP at https://github.com/morrislaptop/firestore-php

**Pull request closed without merging**
