### PR TITLE
Ensure correct ID token verification

### PR DESCRIPTION
**Pull request by jeromegamez**
:octocat:

### CODE REVIEW

**Comment by jeromegamez** [comment]
@hernandev Could you please have a look at this?

**Comment by hernandev** [comment]
are you using the child package or imported the code into this one?

**Comment by hernandev** [comment]
Could not find where the Token\Domain is comming from

**Comment by jeromegamez** [comment]
Yes, I'm using the [kreait/firebase-tokens-php](https://github.com/kreait/firebase-tokens-php): https://github.com/kreait/firebase-tokens-php/blob/master/src/Domain/Verifier.php

It's the Verifier interface, I then inject the implementation in the factory.

**Comment by hernandev** [comment]
@jeromegamez I'm good then. gonna drop you an email now, if that's ok.

Thanks for such a fast fix.

**Comment by hernandev** [comment]
@jeromegamez I'm available to finish it up testing after upgrade to ensure it's all good.

Your email is not public, so just say hi at diego@hernandev.com just for me to tell you some quick tips

**Pull request merged**
