### PR TITLE
Addded missing environment variable

### PR DESCRIPTION
**Pull request by edi**
Adds support for GOOGLE_APPLICATION_CREDENTIALS, not just FIREBASE_CREDENTIALS

### CODE REVIEW

**Comment by edi** [comment]
This fixes #412 :)

**Comment by jeromegamez** [comment]
Thanks! There's a little more to it, but I'll try to incorporate your change to keep your attribution so that you enter the list of contributors 😅

**Comment by edi** [comment]
Argh, you mean the FactoryTest file, correct? Just noticed it :)

**Comment by jeromegamez** [comment]
Here it is: https://github.com/kreait/firebase-php/commit/9514e100e4bbcdc8349e0f47569ccfd1f7c3ae2e (and GitHub nicely recognizes you ^^)

Once the tests pass, I'll merge it and create a new release so that you can revert your workaround from #412 🥳

Thank you for your contribution, it's much appreciated! 🌺

**Comment by edi** [comment]
A tad more complicated than expected haha. Glad I could be of help.

**Comment by jeromegamez** [comment]
Merged with 797ffb7292dd478bc533989afaeb438b6eae1780, released with [v5.1.1](https://github.com/kreait/firebase-php/releases/tag/5.1.1) 🚀

Thanks again!

**Pull request closed without merging**
