### PR TITLE
Fix AndroidConfig's TTL not allowing null

### LINKED ISSUE #719: Android config PR #714 breaks future installations
### Describe the issue you are experiencing

I'm not sure with others, but the PR #714 just broke all my notifications in my Laravel app, because there was no default TTL set, the exception that I was suddenly getting:

```
The TTL of an AndroidConfig must be an positive integer or string matching /^\d+s$/
```

I would've expected to have some backwards compatibility with this if there's no TTL set from out the user, which is 4 weeks default: https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages/#androidconfig

```
How long (in seconds) the message should be kept in FCM storage if the device is offline. The maximum time to live supported is 4 weeks, and the default value is 4 weeks if not set. Set it to 0 if want to send the message immediately. In JSON format, the Duration type is encoded as a string rather than an object, where the string ends in the suffix "s" (indicating seconds) and is preceded by the number of seconds, with nanoseconds expressed as fractional seconds. For example, 3 seconds with 0 nanoseconds should be encoded in JSON format as "3s", while 3 seconds and 1 nanosecond should be expressed in JSON format as "3.000000001s". The ttl will be rounded down to the nearest second.
```

### Installed packages

laravel/framework
kreait/laravel-firebase

### PHP version and extensions

PHP 8.1

### On which operating system(s) does the issue occur?

- [ ] Linux
- [X] MacOS
- [ ] Windows

### Steps to reproduce the issue.

**Breaks:**
```php
->setAndroid(
    AndroidConfig::create()
        ->setFcmOptions(AndroidFcmOptions::create()->setAnalyticsLabel('analytics'))
        ->setNotification(AndroidNotification::create()->setSound('default'))
)
```

**Works:**

```php
->setAndroid(
    AndroidConfig::create()
        ->setTtl(4 * 604800)
        ->setFcmOptions(AndroidFcmOptions::create()->setAnalyticsLabel('analytics'))
        ->setNotification(AndroidNotification::create()->setSound('default'))
)

```

### Error message/Stack trace

```
The TTL of an AndroidConfig must be an positive integer or string matching /^\d+s$/
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by jeromegamez**
Fixes #719 

:octocat:

### CODE REVIEW

**Comment by jeromegamez** [comment]
@Cannonb4ll @Glennmen Don't mind the failing integration tests, I have one too brittle test inside, and regular Firebase Service Glitches when testing APNS configs.

**Comment by jeromegamez** [comment]
If the changes look okay to you, I would merge the PR and create a new release. If you'd prefer to test the branch first, let me know, then I'll wait 🙏

**Comment by jeromegamez** [comment]
:sigh: I'm rushing it too much, I need to collect myself a little and then fix it for real

**Comment by Cannonb4ll** [comment]
No worries, take your time! As I said, we already covered it by going through each notification and explicitly defining the TTL.

**Comment by jeromegamez** [comment]
It's not my fault, you were throwing money at me 😂 

Jokes aside, the fix is now out with https://github.com/kreait/firebase-php/releases/tag/6.6.1 - let me know if something else doesn't work! 💪 

And thank you!

**Comment by Cannonb4ll** [comment]
😂 I didn't mean it to speed you up, you were very nice and understanding (and quick). You don't see that often in open-source. 🤝

**Pull request merged**
