### PR TITLE
Implement FCM topic management

### PR DESCRIPTION
**Pull request by jeromegamez**
Adds methods to subscribe and unsubscribe devices to and from topics.

### How to test

```php
<?php

declare(strict_types=1);

use Kreait\Firebase;
use Kreait\Firebase\Util\JSON;

require_once __DIR__.'/vendor/autoload.php';

$serviceAccount = Firebase\ServiceAccount::fromJsonFile('/path/to/credentials.json');

$firebase = (new Firebase\Factory())
    ->withServiceAccount($serviceAccount)
    ->create();

$messaging = $firebase->getMessaging();
$tokens = [
    // ...
];

echo JSON::prettyPrint($messaging->subscribeToTopic('foo', $tokens));
echo JSON::prettyPrint($messaging->unsubscribeFromTopic('foo', $tokens));
```

### Todo

- [x] Add tests
- [x] Add documentation

### CODE REVIEW

**Comment by jeromegamez** [comment]
FYI @nachocifu @saishsali 

I don't know if it is because of my janky "my own browser is my only registration token and I get a notification on each test run" setup, but I expected that the `results` array in the response body includes error and success counts.

It would be great if you could test this with real devices and confirm/disconfirm my observation :).

**Comment by nachocifu** [comment]
@jeromegamez Hi!
Didnt understand, you want me to test this ? (id be glad to)

**Comment by jeromegamez** [comment]
@nachocifu You don't **have** to, of course, but since you opened #199, I though you would be interested :)

**Comment by nachocifu** [comment]
@jeromegamez got the following
`{ "results": [ [], [] ] }{ "results": [ [], [] ] }`
on my code:

$tokens = array(...);  
echo JSON::prettyPrint($this->messaging->subscribeToTopic('foo', $tokens));   
echo JSON::prettyPrint($this->messaging->unsubscribeFromTopic('foo', $tokens));

**Comment by nachocifu** [comment]
@jeromegamez used two tokens, one for an iOS device and another for android

**Comment by jeromegamez** [comment]
Yes - but if you get results (even if empty), the request was successful. When I used a non-existing registration token, I got an error.

**Comment by jeromegamez** [comment]
Just good to know, so that's probably something on Google's side.

**Comment by jeromegamez** [comment]
You already helped a lot, thank you!

I will have to add the unit/integration tests and update the documentation, but all should be ready at the beginning of next week.

**Comment by lashae** [comment]
@jeromegamez You, two are too fast! I would like to test but I didn't have time last two days and now it seems it's already done.

**Comment by jeromegamez** [comment]
Merged and released with [4.8.0](https://github.com/kreait/firebase-php/releases/tag/4.8.0) 🎉

**Pull request closed without merging**
