### PR TITLE
Rework the action link handling for better resilience and flexibility

### PR DESCRIPTION
**Pull request by jeromegamez**
Implementation of the feature request in #359, including a rework of the handling in general

### How to use

Add `"kreait/firebase-php": "dev-action-links"` to your composer.json file

```php
use Kreait\Firebase\Auth\CreateActionLink\FailedToCreateActionLink;
use Kreait\Firebase\Auth\CreateActionLink\FailedToSendActionLink;

$email = 'user@domain.tld';
$actionCodeSettings = null; // Optional: null, array, or instance of ActionCodeSettings (see below)
$locale = null; // Optional: string|null

$auth = $factory->createAuth();

// Get the action links to use in custom emails
try {
    echo $auth->getPasswordResetLink($email, $actionCodeSettings).PHP_EOL;
    echo $auth->getEmailVerificationLink($email, $actionCodeSettings).PHP_EOL;
    echo $auth->getSignInWithEmailLink($email, $actionCodeSettings).PHP_EOL;
} catch (FailedToCreateActionLink $e) {
    // ...
}

// Let firebase send the emails for us

try {
    $auth->sendPasswordResetLink($email, $actionCodeSettings, 
$locale);
    $auth->sendEmailVerificationLink($email, $actionCodeSettings, $locale);
    $auth->sendSignInWithEmailLink($email, $actionCodeSettings, $locale);
} catch (FailedToSendActionLink $e) {
    // ...
}
```

#### Action code settings

Can be provided as an array, the following keys are supported:

- `continueUrl`/`url`
- `canHandleCodeInApp`
- `dynamicLinkDomain`
- `androidPackageName`
- `androidMinimumVersion`
- `androidInstallApp`
- `iOSBundleId`

### Todo

- [x] Add support for action code settings (the class is already there, but neither worked out nor used 🤷‍♂)
- [x] Validate action code settings
- [x] Add/Modify tests
- [ ] Add/Modify documentation
- [x] Let the existing methods use the new methods
- [x] Add more convenience methods OR deprecate existing convenience methods 🤔 
- [x] `Auth::sendEmailVerification()`/`Auth::sendEmailActionLink('VERIFY_EMAIL')` is currently broken, apparently the email is not enough, the API endpoint needs an ID token as well (see https://github.com/firebase/firebase-js-sdk/issues/1958)

:octocat:

### CODE REVIEW

**Comment by jeromegamez** [comment]
@mkilmanas I think the feature is ready (please note the updated usage in the PR description). The only missing part is the hardest: update the documentation 😅. Please let me know if something doesn't work out in case you test this again 🙏

**Comment by mkilmanas** [comment]
@jeromegamez - I've just tried the updated version and it seems to be running smoothly 👍 My main focus was on `getSignInWithEmailLink(...)` but I've also tried the others at least once as well.
Continue URL is working via actionCodeSettings fine 👍 
A couple of things to note (may or may not need changing):

- [Official Docs](https://firebase.google.com/docs/auth/admin/email-action-links#initialize_actioncodesettings) say that parameter name for ActionCodeSettings is called `url` and then interpreted/used as `continueUrl`, however in your implementation the setting has to be named 'continueUrl' in order for it to work. Not a huge issue, but may be misleading to others as it deviates from the docs;
 - Class names for ActionCodeSettings implementations are a little strange when used without full namespace:
```php
$actionCodeSettings = new Raw(['foo' => 'bar']); // Raw who?..
```
And I think most people will use it this way, with namespace being at the top in the `use` section
- I love how you made named methods for each use case instead of public generic one 👍 But in your usage example above you forgot to remove the first parameter from the `sendXYZ()` calls
Thanks for the great work and a superb quick turnaround - greatly appreciated 🍻

**Comment by jeromegamez** [comment]
Thank you for your feedback! I renamed the classes to `RawActionCodeSettings` and `ValidatedActionCodeSettings` to make the usage clearer (I always switch in my thinking of preferring explicit names and "composed" names from namespace + class name, where I then say "You could always do `use Long\Namespace\Short\Class as ShortClass`, but here I obviously want to please you 😂 )

Concerning the action code settings, I added `url` as a synonym to `continueUrl` to cover both cases - but the inconsistencies to the official documentation are still there, e.g. where I support `iOSBundleId`, the Admin Node SDK wants developers to use `{"iOS": {"bundleId": "xxx"}}`. I have some components that are slightly different in parameter and methods names than the official SDKs, but I also have my "own" documentation, so I hope developers look at that first instead of trying to apply the official docs 1:1 to this SDK. What do you think about it?

**Comment by jeromegamez** [comment]
@mkilmanas I just update the docs in https://github.com/kreait/firebase-php/blob/action-links/docs/user-management.rst#using-email-action-codes and I think the feature is ready now. You have until the end of the current build to object 😂 

No, seriously: if there's something missing or needing a change, I think we can do it separately - at the moment I don't think there should be a no-go left.

Thank you so much for your cooperation and for testing this (and of course for triggering me in the first place) :hibi

**Comment by mkilmanas** [comment]
No, thank you for your rapid implementation and great communication 👍

**Pull request merged**
